# This is a basic workflow to help you get started with Actions

name: develop&feature CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the develop and git workflow branch
  push:
    branches: [ develop, feature/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # .Net for neoxp
        dotnet-version: [ '5.0.x' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install neoxp from dotnet tool
      - name: Install neoxp
        run: |
          sudo apt install libsnappy-dev libc6-dev librocksdb-dev -y
          dotnet tool install --global Neo.Express --version 2.0.39-preview

      # Run neoxp in background
      - name: Run neoxp
        run: neoxp run -s 3 >> neo.log &
        
      # wait for 3s
      - name: Wait
        run: sleep 3
