# This is a basic workflow to help you get started with Actions

name: develop&feature CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push for the develop and git workflow branch
  push:
    branches: [ develop, feature/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install neoxp from dotnet tool
      - name: Install neoxp
        run: |
          wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get install -y dotnet-sdk-5.0
          sudo apt-get install libsnappy-dev libc6-dev librocksdb-dev -y
          dotnet tool install --global Neo.Express --version 2.0.39-preview
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Run neoxp in background
      - name: Start up neoxp
        run: neoxp run -i devnet.neo-express -s 3 >> neo.log &
        
      # Test using gradle
      - name: Unit test
        run: ./gradlew test
