name: develop&feature CI

on:
  push:
    branches: [ develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  contract_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      # Test using gradle
      - name: Unit test
        run: ./gradlew test
        
      # Publish the test report
      - name: Publish Test Report
        if: ${{ !cancelled() }}
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
